// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "@repo/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: config.DATABASE_URL,
  },
});
